services:
  - type: web
    name: backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    region: singaore  # Change as needed
    repo: https://github.com/fasinabsons/backend
    branch: main
    autoDeploy: true  # Auto deploys on push
